apiVersion: v1
kind: Service
metadata:  
  name: user-service
spec:
  selector:    
    name: nagarro-shop-user-service
  type: ClusterIP
  ports:  
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagarro-shop-user-service
  labels:
    name: nagarro-shop-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nagarro-shop-user-service
  template:
    metadata:
      labels:
        name: nagarro-shop-user-service
    spec:
      containers:
      - name: nagarro-shop-user-service
        image: prakhar/nagarro-shop-user-service:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.2"
            memory: "0.5Gi"
          requests:
            cpu: "0.2"
            memory: "0.5Gi"