apiVersion: v1
kind: Service
metadata:  
  name: zipkin-service
spec:
  selector:    
    name: zipkin
  type: LoadBalancer
  ports:  
  - name: http
    port: 9411
    targetPort: 9411
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  labels:
    name: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zipkin
  template:
    metadata:
      labels:
        name: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin
        ports:
        - containerPort: 9411
        env:
        - name: STORAGE_TYPE
          value: mysql
        - name: MYSQL_HOST
          value: zipkin-mysql.default.svc.cluster.local
        resources:
          limits:
            cpu: "0.2"
            memory: "0.5Gi"
          requests:
            cpu: "0.1"
            memory: "0.5Gi"